import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import LoginBtn from './LoginBtn';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="navbar">
          <Link href={'/'} className="logo">
            HOMEPGE
          </Link>
          <Link href={'/list'}>LISTPGE</Link>
          <Link href={'/write'} prefetch={false}>
            WRITEPGE
          </Link>
          <LoginBtn session={session} />
        </header>
        {children}
      </body>
    </html>
  );
}
